import { User, Warehouse, Carton, FlyingProposal, Customer, LedgerEntry, AuditLog } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-master',
    name: 'সুপার এডমিন (Super Admin)',
    email: 'superadmin@cargo.com',
    password: 'Cargo@2026',
    role: 'super_admin',
    status: 'active',
    created_at: '2026-01-01T00:00:00Z',
  },
];

export const INITIAL_WAREHOUSES: Warehouse[] = [
  {
    id: 'wh-china',
    name: 'গুয়াংজু ওয়্যারহাউজ (Guangzhou Air Cargo Hub)',
    country: 'China 🇨🇳',
    code: 'CAN-01',
    hub_type: 'origin',
    is_final_destination: false,
    address: 'No. 88 Logistics Park, Baiyun District, Guangzhou, Guangdong',
    city: 'Guangzhou',
    phone: '+86 20 8899-7711',
    status: 'active',
    total_cartons: 420,
    incharge_staff: [
      {
        id: 'usr-3',
        name: 'চেন ওয়েই (Chen Wei)',
        email: 'china@fourstarcargo.com',
        phone: '+86 138-0013-8000',
        role: 'warehouse_incharge',
        status: 'active',
        created_at: '2026-01-10T00:00:00Z',
      },
    ],
  },
  {
    id: 'wh-hk',
    name: 'হংকং ওয়্যারহাউজ (Hong Kong Cargo Terminal)',
    country: 'Hong Kong 🇭🇰',
    code: 'HKG-01',
    hub_type: 'origin',
    is_final_destination: false,
    address: 'Unit 4B, Asia Airfreight Terminal, Hong Kong International Airport',
    city: 'Hong Kong',
    phone: '+852 2388-9900',
    status: 'active',
    total_cartons: 185,
    incharge_staff: [
      {
        id: 'usr-4',
        name: 'লি কা-শিং (Li Ka-shing)',
        email: 'hk@fourstarcargo.com',
        phone: '+852 9123-4567',
        role: 'warehouse_incharge',
        status: 'active',
        created_at: '2026-01-12T00:00:00Z',
      },
    ],
  },
  {
    id: 'wh-dubai',
    name: 'দুবাই ওয়্যারহাউজ (Dubai Cargo Village Hub)',
    country: 'UAE 🇦🇪',
    code: 'DXB-01',
    hub_type: 'origin',
    is_final_destination: false,
    address: 'Gate 5, DAFZA Cargo Terminal, Dubai International Airport',
    city: 'Dubai',
    phone: '+971 4 299-8800',
    status: 'active',
    total_cartons: 140,
    incharge_staff: [
      {
        id: 'usr-4b',
        name: 'তারিক মানসুর (Tariq Mansoor)',
        email: 'dubai@fourstarcargo.com',
        phone: '+971 50 123-4567',
        role: 'warehouse_incharge',
        status: 'active',
        created_at: '2026-02-01T00:00:00Z',
      },
    ],
  },
  {
    id: 'wh-bd',
    name: 'ঢাকা সেন্ট্রাল ওয়্যারহাউজ (Dhaka Central Freight Hub)',
    country: 'Bangladesh 🇧🇩',
    code: 'DAC-01',
    hub_type: 'destination',
    is_final_destination: true,
    address: 'প্লট ৪৫, তেজগাঁও শিল্প এলাকা, ঢাকা-১২০৮',
    city: 'Dhaka',
    phone: '+880 1711-009988',
    status: 'active',
    total_cartons: 310,
    incharge_staff: [
      {
        id: 'usr-5',
        name: 'রফিকুল ইসলাম (Rafiqul Islam)',
        email: 'bd@fourstarcargo.com',
        phone: '+880 1819-445566',
        role: 'warehouse_incharge',
        status: 'active',
        created_at: '2026-01-15T00:00:00Z',
      },
    ],
  },
];

export const INITIAL_CARTONS: Carton[] = [
  {
    id: 'ctn-seed-101',
    ctn_no: 'CTN-US03-01',
    shipping_mark: 'FSC-2026-US03',
    tracking_number: 'FSC-2026-US03',
    product_name_en: 'Guangzhou Electronics',
    quantity: 1,
    net_weight: 45.0,
    gross_weight: 45.0,
    cbm: 0.4,
    current_warehouse_id: 'wh-china',
    destination_warehouse_id: 'wh-bd',
    status: 'proposed',
    flight_number: 'US-03',
    booked_by: 'usr-1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ctn-seed-102',
    ctn_no: 'CTN-US03-02',
    shipping_mark: 'FSC-2026-US03',
    tracking_number: 'FSC-2026-US03',
    product_name_en: 'Guangzhou Electronics',
    quantity: 1,
    net_weight: 52.0,
    gross_weight: 52.0,
    cbm: 0.5,
    current_warehouse_id: 'wh-china',
    destination_warehouse_id: 'wh-bd',
    status: 'proposed',
    flight_number: 'US-03',
    booked_by: 'usr-1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_PROPOSALS: FlyingProposal[] = [
  {
    id: 'prop-us03-master',
    flying_name: 'US-03',
    flight_number: 'US-03',
    warehouse_id: 'wh-china',
    warehouse_name: 'চীন (গুয়াংজু হাব) CN',
    destination_warehouse_id: 'wh-bd',
    destination_warehouse_name: 'বাংলাদেশ (ঢাকা সেন্ট্রাল হাব) BD',
    proposed_by: 'usr-1',
    proposed_by_name: 'তানভীর আহমেদ (China Incharge)',
    date: '2026-08-18',
    status: 'pending',
    carton_ids: ['ctn-seed-101', 'ctn-seed-102'],
    items_count: 6,
    total_weight: 185.0,
    total_cbm: 2.4,
    airline: 'US-Bangla Air Cargo',
  },
];
export const INITIAL_CUSTOMERS: Customer[] = [];
export const INITIAL_LEDGER: LedgerEntry[] = [];
export const INITIAL_AUDIT_LOGS: AuditLog[] = [];
export const INITIAL_EXPENSES = [];

export const INITIAL_CRM_CUSTOMERS = [
  {
    id: 'crm-cust-101',
    name: 'Syeda Masuka',
    phone: '01828661711',
    country_category: 'CN_Old',
    followup_status: 'followup',
    notes: 'Inquired about Guangzhou air shipping rate per kg',
    created_by: 'তানভীর আহমেদ (CRM Ex-1)',
    created_by_id: 'usr-crm-01',
    created_at: '2026-08-15T10:00:00Z',
    date: '15.08.26',
    is_handed_over: false,
  },
  {
    id: 'crm-cust-102',
    name: 'SOHAN',
    phone: '01761978757',
    country_category: 'CN_Old',
    followup_status: 'followup',
    notes: 'Has 300kg garment accessories ready in Yiwu',
    created_by: 'রফিক ইসলাম (CRM Ex-2)',
    created_by_id: 'usr-crm-02',
    created_at: '2026-08-15T11:30:00Z',
    date: '15.08.26',
    is_handed_over: false,
  },
  {
    id: 'crm-cust-103',
    name: 'Jafar',
    phone: '82 10-5860-0604',
    country_category: 'KR_Old',
    followup_status: 'followup',
    notes: 'Korea beauty products importer - requested quote',
    created_by: 'তানভীর আহমেদ (CRM Ex-1)',
    created_by_id: 'usr-crm-01',
    created_at: '2026-08-15T12:15:00Z',
    date: '15.08.26',
    is_handed_over: false,
  },
  {
    id: 'crm-cust-104',
    name: 'Faria Jahan Richi',
    phone: '01834026579',
    country_category: 'CN_New',
    followup_status: 'followup',
    notes: 'New buyer looking for Guangzhou warehouse address',
    created_by: 'সাবরিনা সুলতানা (CRM Ex-3)',
    created_by_id: 'usr-crm-03',
    created_at: '2026-08-15T14:00:00Z',
    date: '15.08.26',
    is_handed_over: false,
  },
  {
    id: 'crm-cust-105',
    name: 'Hasan Karar- Hasan IT',
    phone: '01761442394',
    country_category: 'CN_New',
    followup_status: 'order_complete',
    notes: 'First order dispatched on CZ-304 charter flight',
    created_by: 'তানভীর আহমেদ (CRM Ex-1)',
    created_by_id: 'usr-crm-01',
    created_at: '2026-02-03T09:00:00Z',
    date: '03.02.26',
    is_handed_over: true,
    handed_over_at: '2026-02-05T10:00:00Z',
    handed_over_by: 'তানভীর আহমেদ (CRM Ex-1)',
  },
  {
    id: 'crm-cust-106',
    name: 'China I\'m Robiul',
    phone: '01615053601',
    country_category: 'CN_New',
    followup_status: 'order_complete',
    notes: 'Completed 120kg electronics shipment booking',
    created_by: 'রফিক ইসলাম (CRM Ex-2)',
    created_by_id: 'usr-crm-02',
    created_at: '2026-02-03T11:00:00Z',
    date: '03.02.26',
    is_handed_over: true,
    handed_over_at: '2026-02-04T15:30:00Z',
    handed_over_by: 'রফিক ইসলাম (CRM Ex-2)',
  },
  {
    id: 'crm-cust-107',
    name: 'mithila',
    phone: '01644700554',
    country_category: 'CN_New',
    followup_status: 'order_complete',
    notes: 'Regular bags importer - shipment received at Dhaka',
    created_by: 'সাবরিনা সুলতানা (CRM Ex-3)',
    created_by_id: 'usr-crm-03',
    created_at: '2026-02-03T14:20:00Z',
    date: '03.02.26',
    is_handed_over: true,
    handed_over_at: '2026-02-06T11:00:00Z',
    handed_over_by: 'সাবরিনা সুলতানা (CRM Ex-3)',
  },
  {
    id: 'crm-cust-108',
    name: 'sipon islam',
    phone: '82 10-5828-8316',
    country_category: 'KR_New',
    followup_status: 'order_complete',
    notes: 'Korea to Dhaka air cargo booking completed',
    created_by: 'তানভীর আহমেদ (CRM Ex-1)',
    created_by_id: 'usr-crm-01',
    created_at: '2026-02-03T16:00:00Z',
    date: '03.02.26',
    is_handed_over: true,
    handed_over_at: '2026-02-04T09:10:00Z',
    handed_over_by: 'তানভীর আহমেদ (CRM Ex-1)',
  },
  {
    id: 'crm-cust-109',
    name: 'Abdullah Al Noman',
    phone: '01759830969',
    country_category: 'CN_Old',
    followup_status: 'important_regular',
    notes: 'VIP customer - monthly 2 tons air freight volume',
    created_by: 'তানভীর আহমেদ (CRM Ex-1)',
    created_by_id: 'usr-crm-01',
    created_at: '2026-08-15T09:30:00Z',
    date: '15.08.26',
    is_handed_over: true,
    handed_over_at: '2026-08-16T12:00:00Z',
    handed_over_by: 'তানভীর আহমেদ (CRM Ex-1)',
  },
  {
    id: 'crm-cust-110',
    name: 'MD Miskat',
    phone: '01985045908',
    country_category: 'CN_Old',
    followup_status: 'important_regular',
    notes: 'Regular shoes & fabric importer from Guangzhou',
    created_by: 'রফিক ইসলাম (CRM Ex-2)',
    created_by_id: 'usr-crm-02',
    created_at: '2026-08-15T11:00:00Z',
    date: '15.08.26',
    is_handed_over: true,
    handed_over_at: '2026-08-16T14:20:00Z',
    handed_over_by: 'রফিক ইসলাম (CRM Ex-2)',
  },
  {
    id: 'crm-cust-111',
    name: 'Habibur Rahman',
    phone: '01674152133',
    country_category: 'CN_Old',
    followup_status: 'important_regular',
    notes: 'Weekly 500kg regular shipment booking',
    created_by: 'সাবরিনা সুলতানা (CRM Ex-3)',
    created_by_id: 'usr-crm-03',
    created_at: '2026-08-15T15:10:00Z',
    date: 'Regular',
    is_handed_over: true,
    handed_over_at: '2026-08-16T16:00:00Z',
    handed_over_by: 'সাবরিনা সুলতানা (CRM Ex-3)',
  },
];
