import { User, Warehouse, Carton, FlyingProposal, Customer, LedgerEntry, AuditLog } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-master',
    name: 'সুপার এডমিন (Super Admin)',
    email: 'superadmin@cargo.com',
    role: 'super_admin',
    status: 'active',
    created_at: '2026-01-01T00:00:00Z',
  },
];

export const INITIAL_WAREHOUSES: Warehouse[] = [
  {
    id: 'wh-china',
    name: 'গুয়াংজু ওয়্যারহাউজ (Guangzhou Air Cargo Hub)',
    country: 'China 🇨🇳',
    code: 'CAN-01',
    hub_type: 'origin',
    is_final_destination: false,
    address: 'No. 88 Logistics Park, Baiyun District, Guangzhou, Guangdong',
    city: 'Guangzhou',
    phone: '+86 20 8899-7711',
    status: 'active',
    total_cartons: 420,
    incharge_staff: [
      {
        id: 'usr-3',
        name: 'চেন ওয়েই (Chen Wei)',
        email: 'china@fourstarcargo.com',
        phone: '+86 138-0013-8000',
        role: 'warehouse_incharge',
        status: 'active',
        created_at: '2026-01-10T00:00:00Z',
      },
    ],
  },
  {
    id: 'wh-hk',
    name: 'হংকং ওয়্যারহাউজ (Hong Kong Cargo Terminal)',
    country: 'Hong Kong 🇭🇰',
    code: 'HKG-01',
    hub_type: 'origin',
    is_final_destination: false,
    address: 'Unit 4B, Asia Airfreight Terminal, Hong Kong International Airport',
    city: 'Hong Kong',
    phone: '+852 2388-9900',
    status: 'active',
    total_cartons: 185,
    incharge_staff: [
      {
        id: 'usr-4',
        name: 'লি কা-শিং (Li Ka-shing)',
        email: 'hk@fourstarcargo.com',
        phone: '+852 9123-4567',
        role: 'warehouse_incharge',
        status: 'active',
        created_at: '2026-01-12T00:00:00Z',
      },
    ],
  },
  {
    id: 'wh-dubai',
    name: 'দুবাই ওয়্যারহাউজ (Dubai Cargo Village Hub)',
    country: 'UAE 🇦🇪',
    code: 'DXB-01',
    hub_type: 'origin',
    is_final_destination: false,
    address: 'Gate 5, DAFZA Cargo Terminal, Dubai International Airport',
    city: 'Dubai',
    phone: '+971 4 299-8800',
    status: 'active',
    total_cartons: 140,
    incharge_staff: [
      {
        id: 'usr-4b',
        name: 'তারিক মানসুর (Tariq Mansoor)',
        email: 'dubai@fourstarcargo.com',
        phone: '+971 50 123-4567',
        role: 'warehouse_incharge',
        status: 'active',
        created_at: '2026-02-01T00:00:00Z',
      },
    ],
  },
  {
    id: 'wh-bd',
    name: 'ঢাকা সেন্ট্রাল ওয়্যারহাউজ (Dhaka Central Freight Hub)',
    country: 'Bangladesh 🇧🇩',
    code: 'DAC-01',
    hub_type: 'destination',
    is_final_destination: true,
    address: 'প্লট ৪৫, তেজগাঁও শিল্প এলাকা, ঢাকা-১২০৮',
    city: 'Dhaka',
    phone: '+880 1711-009988',
    status: 'active',
    total_cartons: 310,
    incharge_staff: [
      {
        id: 'usr-5',
        name: 'রফিকুল ইসলাম (Rafiqul Islam)',
        email: 'bd@fourstarcargo.com',
        phone: '+880 1819-445566',
        role: 'warehouse_incharge',
        status: 'active',
        created_at: '2026-01-15T00:00:00Z',
      },
    ],
  },
];

export const INITIAL_CARTONS: Carton[] = [
  {
    id: 'ctn-bs02-1',
    ctn_no: 'CTN-01',
    shipping_mark: 'SM-DHAKA-88',
    tracking_number: 'TRK-BS02-101',
    master_tracking_number: 'TRK-BS02-101',
    product_name_en: 'Solar Inverter Modules & Electronics',
    product_name_cn: '光伏逆变器模块',
    quantity: 10,
    net_weight: 2.0,
    gross_weight: 2.25,
    cbm: 0.15,
    current_warehouse_id: 'wh-china',
    destination_warehouse_id: 'wh-bd',
    status: 'in_transit',
    flight_number: 'BS-206',
    awb_number: '157-884120',
    flying_date: '2026-08-16',
    booked_by: 'usr-3',
    created_at: '2026-08-16T09:30:00Z',
    updated_at: '2026-08-16T09:30:00Z',
    current_warehouse_name: 'গুয়াংজু ওয়্যারহাউজ',
    destination_warehouse_name: 'ঢাকা সেন্ট্রাল',
  },
  {
    id: 'ctn-bs02-2',
    ctn_no: 'CTN-02',
    shipping_mark: 'SM-DHAKA-88',
    tracking_number: 'TRK-BS02-102',
    master_tracking_number: 'TRK-BS02-102',
    product_name_en: 'Solar Inverter Cable & Connectors',
    product_name_cn: '光伏连接线缆',
    quantity: 15,
    net_weight: 2.0,
    gross_weight: 2.25,
    cbm: 0.15,
    current_warehouse_id: 'wh-china',
    destination_warehouse_id: 'wh-bd',
    status: 'in_transit',
    flight_number: 'BS-206',
    awb_number: '157-884120',
    flying_date: '2026-08-16',
    booked_by: 'usr-3',
    created_at: '2026-08-16T09:30:00Z',
    updated_at: '2026-08-16T09:30:00Z',
    current_warehouse_name: 'গুয়াংজু ওয়্যারহাউজ',
    destination_warehouse_name: 'ঢাকা সেন্ট্রাল',
  },
  {
    id: 'ctn-bs02-3',
    ctn_no: 'CTN-03',
    shipping_mark: 'SM-DHAKA-88',
    tracking_number: 'TRK-BS02-103',
    master_tracking_number: 'TRK-BS02-103',
    product_name_en: 'LED Smart TV Display Panels',
    product_name_cn: 'LED 智能电视显示屏组件',
    quantity: 5,
    net_weight: 2.0,
    gross_weight: 2.25,
    cbm: 0.15,
    current_warehouse_id: 'wh-china',
    destination_warehouse_id: 'wh-bd',
    status: 'in_transit',
    flight_number: 'BS-206',
    awb_number: '157-884120',
    flying_date: '2026-08-16',
    booked_by: 'usr-3',
    created_at: '2026-08-16T09:30:00Z',
    updated_at: '2026-08-16T09:30:00Z',
    current_warehouse_name: 'গুয়াংজু ওয়্যারহাউজ',
    destination_warehouse_name: 'ঢাকা সেন্ট্রাল',
  },
  {
    id: 'ctn-bs02-4',
    ctn_no: 'CTN-04',
    shipping_mark: 'SM-DHAKA-88',
    tracking_number: 'TRK-BS02-104',
    master_tracking_number: 'TRK-BS02-104',
    product_name_en: 'Smart Watch Accessories & Straps',
    product_name_cn: '智能手表表带',
    quantity: 50,
    net_weight: 2.0,
    gross_weight: 2.25,
    cbm: 0.15,
    current_warehouse_id: 'wh-china',
    destination_warehouse_id: 'wh-bd',
    status: 'in_transit',
    flight_number: 'BS-206',
    awb_number: '157-884120',
    flying_date: '2026-08-16',
    booked_by: 'usr-3',
    created_at: '2026-08-16T09:30:00Z',
    updated_at: '2026-08-16T09:30:00Z',
    current_warehouse_name: 'গুয়াংজু ওয়্যারহাউজ',
    destination_warehouse_name: 'ঢাকা সেন্ট্রাল',
  },
  {
    id: 'ctn-bs02-5',
    ctn_no: 'CTN-05',
    shipping_mark: 'SM-DHAKA-88',
    tracking_number: 'TRK-BS02-105',
    master_tracking_number: 'TRK-BS02-105',
    product_name_en: 'Wireless Earbuds & Bluetooth Speakers',
    product_name_cn: '无线蓝牙耳机',
    quantity: 40,
    net_weight: 2.0,
    gross_weight: 2.25,
    cbm: 0.15,
    current_warehouse_id: 'wh-china',
    destination_warehouse_id: 'wh-bd',
    status: 'in_transit',
    flight_number: 'BS-206',
    awb_number: '157-884120',
    flying_date: '2026-08-16',
    booked_by: 'usr-3',
    created_at: '2026-08-16T09:30:00Z',
    updated_at: '2026-08-16T09:30:00Z',
    current_warehouse_name: 'গুয়াংজু ওয়্যারহাউজ',
    destination_warehouse_name: 'ঢাকা সেন্ট্রাল',
  },
  {
    id: 'ctn-bs02-6',
    ctn_no: 'CTN-06',
    shipping_mark: 'SM-DHAKA-88',
    tracking_number: 'TRK-BS02-106',
    master_tracking_number: 'TRK-BS02-106',
    product_name_en: 'Mobile Phone Tempered Glass Protectors',
    product_name_cn: '手机钢化膜',
    quantity: 100,
    net_weight: 2.0,
    gross_weight: 2.25,
    cbm: 0.15,
    current_warehouse_id: 'wh-china',
    destination_warehouse_id: 'wh-bd',
    status: 'in_transit',
    flight_number: 'BS-206',
    awb_number: '157-884120',
    flying_date: '2026-08-16',
    booked_by: 'usr-3',
    created_at: '2026-08-16T09:30:00Z',
    updated_at: '2026-08-16T09:30:00Z',
    current_warehouse_name: 'গুয়াংজু ওয়্যারহাউজ',
    destination_warehouse_name: 'ঢাকা সেন্ট্রাল',
  },
  {
    id: 'ctn-bs02-7',
    ctn_no: 'CTN-07',
    shipping_mark: 'SM-DHAKA-88',
    tracking_number: 'TRK-BS02-107',
    master_tracking_number: 'TRK-BS02-107',
    product_name_en: 'Industrial Sewing Machine Servo Motors',
    product_name_cn: '缝纫机电机',
    quantity: 2,
    net_weight: 2.0,
    gross_weight: 2.25,
    cbm: 0.15,
    current_warehouse_id: 'wh-china',
    destination_warehouse_id: 'wh-bd',
    status: 'in_transit',
    flight_number: 'BS-206',
    awb_number: '157-884120',
    flying_date: '2026-08-16',
    booked_by: 'usr-3',
    created_at: '2026-08-16T09:30:00Z',
    updated_at: '2026-08-16T09:30:00Z',
    current_warehouse_name: 'গুয়াংজু ওয়্যারহাউজ',
    destination_warehouse_name: 'ঢাকা সেন্ট্রাল',
  },
  {
    id: 'ctn-bs02-8',
    ctn_no: 'CTN-08',
    shipping_mark: 'SM-DHAKA-88',
    tracking_number: 'TRK-BS02-108',
    master_tracking_number: 'TRK-BS02-108',
    product_name_en: 'Microfiber Fabrics & Garment Accessories',
    product_name_cn: '服装辅料',
    quantity: 20,
    net_weight: 2.0,
    gross_weight: 2.25,
    cbm: 0.15,
    current_warehouse_id: 'wh-china',
    destination_warehouse_id: 'wh-bd',
    status: 'in_transit',
    flight_number: 'BS-206',
    awb_number: '157-884120',
    flying_date: '2026-08-16',
    booked_by: 'usr-3',
    created_at: '2026-08-16T09:30:00Z',
    updated_at: '2026-08-16T09:30:00Z',
    current_warehouse_name: 'গুয়াংজু ওয়্যারহাউজ',
    destination_warehouse_name: 'ঢাকা সেন্ট্রাল',
  },
];

export const INITIAL_PROPOSALS: FlyingProposal[] = [
  {
    id: 'prop-bs02',
    flying_name: 'bs-02',
    flight_number: 'BS-206',
    awb_number: '157-884120',
    date: '2026-08-16',
    warehouse_id: 'wh-china',
    warehouse_name: 'গুয়াংজু ওয়্যারহাউজ (Guangzhou Air Cargo Hub)',
    destination_warehouse_id: 'wh-bd',
    destination_warehouse_name: 'ঢাকা সেন্ট্রাল (Dhaka Central Hub)',
    items_count: 8,
    total_weight: 18.0,
    total_cbm: 1.20,
    status: 'in_transit',
    proposed_by: 'usr-3',
    proposed_by_name: 'গুয়াংজু ইনচার্জ',
    carton_ids: [
      'ctn-bs02-1',
      'ctn-bs02-2',
      'ctn-bs02-3',
      'ctn-bs02-4',
      'ctn-bs02-5',
      'ctn-bs02-6',
      'ctn-bs02-7',
      'ctn-bs02-8',
    ],
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-101',
    customer_code: 'CUST-8801',
    shipping_mark: 'SM-DHAKA-88',
    name: 'আল-আমীন ট্রেডার্স (Al-Amin Traders)',
    phone: '+880 1712-345678',
    company_name: 'Al-Amin Electronics Ltd.',
    address: 'দোকান ১২, স্টেডিয়াম মার্কেট, পল্টন, ঢাকা',
    total_due: 45000,
    total_paid: 185000,
    status: 'active',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'cust-102',
    customer_code: 'CUST-8802',
    shipping_mark: 'SM-CHITTAGONG-12',
    name: 'মেসার্স চৌধুরী টেক্সটাইল (Chowdhury Textile)',
    phone: '+880 1819-998877',
    company_name: 'Chowdhury Garments Accessories',
    address: 'রিয়াজউদ্দিন বাজার, সিজিএস কমপ্লেক্স, চট্টগ্রাম',
    total_due: 0,
    total_paid: 320000,
    status: 'vip',
    created_at: '2026-01-12T00:00:00Z',
  },
];

export const INITIAL_LEDGER: LedgerEntry[] = [];
export const INITIAL_AUDIT_LOGS: AuditLog[] = [];
export const INITIAL_EXPENSES = [];
