import { User, Warehouse, Carton, FlyingProposal, Customer, LedgerEntry, AuditLog } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-master',
    name: 'সুপার এডমিন (Super Admin)',
    email: 'superadmin@cargo.com',
    password: 'Cargo@2026',
    role: 'super_admin',
    status: 'active',
    created_at: '2026-01-01T00:00:00Z',
  },
];

export const INITIAL_WAREHOUSES: Warehouse[] = [
  {
    id: 'wh-china',
    name: 'গুয়াংজু ওয়্যারহাউজ (Guangzhou Air Cargo Hub)',
    country: 'China 🇨🇳',
    code: 'CAN-01',
    hub_type: 'origin',
    is_final_destination: false,
    address: 'No. 88 Logistics Park, Baiyun District, Guangzhou, Guangdong',
    city: 'Guangzhou',
    phone: '+86 20 8899-7711',
    status: 'active',
    total_cartons: 420,
    incharge_staff: [
      {
        id: 'usr-3',
        name: 'চেন ওয়েই (Chen Wei)',
        email: 'china@fourstarcargo.com',
        phone: '+86 138-0013-8000',
        role: 'warehouse_incharge',
        status: 'active',
        created_at: '2026-01-10T00:00:00Z',
      },
    ],
  },
  {
    id: 'wh-hk',
    name: 'হংকং ওয়্যারহাউজ (Hong Kong Cargo Terminal)',
    country: 'Hong Kong 🇭🇰',
    code: 'HKG-01',
    hub_type: 'origin',
    is_final_destination: false,
    address: 'Unit 4B, Asia Airfreight Terminal, Hong Kong International Airport',
    city: 'Hong Kong',
    phone: '+852 2388-9900',
    status: 'active',
    total_cartons: 185,
    incharge_staff: [
      {
        id: 'usr-4',
        name: 'লি কা-শিং (Li Ka-shing)',
        email: 'hk@fourstarcargo.com',
        phone: '+852 9123-4567',
        role: 'warehouse_incharge',
        status: 'active',
        created_at: '2026-01-12T00:00:00Z',
      },
    ],
  },
  {
    id: 'wh-dubai',
    name: 'দুবাই ওয়্যারহাউজ (Dubai Cargo Village Hub)',
    country: 'UAE 🇦🇪',
    code: 'DXB-01',
    hub_type: 'origin',
    is_final_destination: false,
    address: 'Gate 5, DAFZA Cargo Terminal, Dubai International Airport',
    city: 'Dubai',
    phone: '+971 4 299-8800',
    status: 'active',
    total_cartons: 140,
    incharge_staff: [
      {
        id: 'usr-4b',
        name: 'তারিক মানসুর (Tariq Mansoor)',
        email: 'dubai@fourstarcargo.com',
        phone: '+971 50 123-4567',
        role: 'warehouse_incharge',
        status: 'active',
        created_at: '2026-02-01T00:00:00Z',
      },
    ],
  },
  {
    id: 'wh-bd',
    name: 'ঢাকা সেন্ট্রাল ওয়্যারহাউজ (Dhaka Central Freight Hub)',
    country: 'Bangladesh 🇧🇩',
    code: 'DAC-01',
    hub_type: 'destination',
    is_final_destination: true,
    address: 'প্লট ৪৫, তেজগাঁও শিল্প এলাকা, ঢাকা-১২০৮',
    city: 'Dhaka',
    phone: '+880 1711-009988',
    status: 'active',
    total_cartons: 310,
    incharge_staff: [
      {
        id: 'usr-5',
        name: 'রফিকুল ইসলাম (Rafiqul Islam)',
        email: 'bd@fourstarcargo.com',
        phone: '+880 1819-445566',
        role: 'warehouse_incharge',
        status: 'active',
        created_at: '2026-01-15T00:00:00Z',
      },
    ],
  },
];

export const INITIAL_CARTONS: Carton[] = [
  {
    id: 'ctn-seed-101',
    ctn_no: 'CTN-US03-01',
    shipping_mark: 'FSC-2026-US03',
    tracking_number: 'FSC-2026-US03',
    product_name_en: 'Guangzhou Electronics',
    quantity: 1,
    net_weight: 45.0,
    gross_weight: 45.0,
    cbm: 0.4,
    current_warehouse_id: 'wh-china',
    destination_warehouse_id: 'wh-bd',
    status: 'proposed',
    flight_number: 'US-03',
    booked_by: 'usr-1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ctn-seed-102',
    ctn_no: 'CTN-US03-02',
    shipping_mark: 'FSC-2026-US03',
    tracking_number: 'FSC-2026-US03',
    product_name_en: 'Guangzhou Electronics',
    quantity: 1,
    net_weight: 52.0,
    gross_weight: 52.0,
    cbm: 0.5,
    current_warehouse_id: 'wh-china',
    destination_warehouse_id: 'wh-bd',
    status: 'proposed',
    flight_number: 'US-03',
    booked_by: 'usr-1',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_PROPOSALS: FlyingProposal[] = [
  {
    id: 'prop-us03-master',
    flying_name: 'US-03',
    flight_number: 'US-03',
    warehouse_id: 'wh-china',
    warehouse_name: 'চীন (গুয়াংজু হাব) CN',
    destination_warehouse_id: 'wh-bd',
    destination_warehouse_name: 'বাংলাদেশ (ঢাকা সেন্ট্রাল হাব) BD',
    proposed_by: 'usr-1',
    proposed_by_name: 'তানভীর আহমেদ (China Incharge)',
    date: '2026-08-18',
    status: 'pending',
    carton_ids: ['ctn-seed-101', 'ctn-seed-102'],
    items_count: 6,
    total_weight: 185.0,
    total_cbm: 2.4,
    airline: 'US-Bangla Air Cargo',
  },
];
export const INITIAL_CUSTOMERS: Customer[] = [];
export const INITIAL_LEDGER: LedgerEntry[] = [];
export const INITIAL_AUDIT_LOGS: AuditLog[] = [];
export const INITIAL_EXPENSES = [];
